### ISSUE TITLE
GETTING STARTED.md filename incorrect

### ISSUE THREAD

**Issue by NedWilbur** [alekdavis/PlexBackup#16]
Reference: https://github.com/alekdavis/PlexBackup/blob/master/GETTING%20STARTED.md#rename-sample-config-file

**Correction**: Rename PlexBackup.ps1.SAMPLE.json file to **PlexBackup.json** and make sure it's located in the same folder as PlexBackup.ps1.

**Comment by alekdavis** [comment]
That would be incorrect. The file should be renamed to `PlexBackup.ps1.json`, just as the instructions say. Technically, you can name the config file whatever you want, but if you do not use the default naming convention (i.e. `script_file_name.ps1.json`), you need to specify the file path via a command-line switch.

**Comment by NedWilbur** [comment]
Hmm, perhaps I am experiencing a different issue. Nonetheless, seems to be working with `PlexBackup.json` file. Thanks for the information. 
![image](https://user-images.githubusercontent.com/19377058/60822767-1610f880-a174-11e9-89b0-da2c3ee81d83.png)

![image](https://user-images.githubusercontent.com/19377058/60822776-19a47f80-a174-11e9-9faa-09f5af681e04.png)

**Comment by alekdavis** [comment]
It looks like there may be an issue with the config (.json) file. When you change the file name to `PlexBackup.json` but do not pass its path via command-line switch (which seems to be the case), the script simply ignores it and uses the defaults. Try invoking `PlexBackup.ps1` with the `-ConfigFile PathToYourPlexBackup.jsonFile` switch and I suspect you will get the same error. Could you post the contents of your config file?

**Comment by NedWilbur** [comment]
Figured it out @alekdavis, one of my `/` was not escaped... Thanks for the help and for the awesome script.

**Comment by alekdavis** [comment]
Coll. Thanks for the update.
