### ISSUE TITLE
Cannot find Plex Media Server executable file

### ISSUE THREAD

**Issue by SANSd20** [alekdavis/PlexBackup#17]
When running the script, I get the following error, but when running test path, it finds it.

```
PS C:\Users\Admin\Desktop\PlexBackup-master> .\PlexBackup.ps1
PlexBackup v1.5.10 (c) 2019 Alek Davis
Script started at:
  09/01/2019 09:15:19
Operation mode:
  BACKUP
Backup type:
  DEFAULT
Cannot find Plex Media Server executable file:
  C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
PS C:\Users\Admin\Desktop\PlexBackup-master> Test-Path 'C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe'
True
PS C:\Users\Admin\Desktop\PlexBackup-master>
```

**Comment by alekdavis** [comment]
It looks like you have two instances of Plex Media Server running (see the path is duplicated?). This does not seem normal. Could you check Task Manager and see how many instances are active?

**Comment by SANSd20** [comment]
Looks like I had at least 2. I have been having issues with PaaS and Plex since the last few updates. 

I ended everything that had “Plex” in it and relaunched Plex. It is working now.
