### ISSUE TITLE
7z parameters for performance?

### ISSUE THREAD

**Issue by admaxey** [alekdavis/PlexBackup#18]
Is there a way your script could pass parameters to 7-zip to increase performance? I have a Plex system with 28 cores, 384GB of RAM, and NVME SSD storage - a backup operation currently uses ~5% CPU and about 5GB of RAM and takes about 90 mins to complete. It appears that 7z has some switches for memory usage and multithreading. Have you considered allowing usage of these parameters?

https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm

**Comment by alekdavis** [comment]
I have, but I was afraid it would confuse most users. Which particular parameters would you want to be configurable?

**Comment by patrix87** [comment]
Reducing the level of compression would greatly increase performance. Setting it to 1 would still reduce the fill size a lot but would make the backup take seconds instead of minutes.

**Comment by alekdavis** [comment]
@patrix87 : What about other flags (like the CPU utilization)? Wouldn't they need to be configurable as well?

**Comment by yangqi** [comment]
After reading the docs, 7z has multithreading 'on' by default. However, the LZMA2 algorithm it chooses only use 2 thread by default for following reason. 

> mt=[off | on | {N}]
Sets multithread mode. If you have a multiprocessor or multicore system, you can get a increase with this switch. 7-Zip supports multithread mode only for LZMA / LZMA2 compression and BZip2 compression / decompression. If you specify {N}, for example mt=4, 7-Zip tries to use 4 threads. LZMA compression uses only 2 threads.

> LZMA2 uses: 1 thread for each chunk in x1 and x3 modes; and 2 threads for each chunk in x5, x7 and x9 modes. If LZMA2 is set to use only such number of threads required for one chunk, it doesn't split stream to chunks. So you can get different compression ratio for different number of threads. You can get the best compression ratio, when you use 1 or 2 threads.

**Comment by alekdavis** [comment]
Implemented in v1.7.0. You can specify optional 7-zip switches for compression and decompression in the configuration file.
