### ISSUE TITLE
Doesn't work with Powershell 6.2.3

### ISSUE THREAD

**Issue by Kholtien** [alekdavis/PlexBackup#19]
When I run the backup using Powershell Core 6.2.3 I get the following error

> LogException : The term 'Start-BitsTransfer' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At E:\MediaKitBackup\PlexBackup\PlexBackup.ps1:2275 char:17
> \+                 LogException $_
> \+                 ~~~~~~~~~~~~~~~
> \+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
> \
[Backup.err.log](https://github.com/alekdavis/PlexBackup/files/3896653/Backup.err.log)
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LogException

**Comment by alekdavis** [comment]
Any particular reason why you must use PowerShell Core? I am not sure what I can do here if this cmdlet is missing from PowerShell Core.

**Comment by Kholtien** [comment]
It’s more so it can be included in the documentation I guess rather than fixing it.
