### ISSUE TITLE
7zip and Scheduled Plex backup

### ISSUE THREAD

**Issue by Galiwyx** [alekdavis/PlexBackup#23]
Hello,

I want to use 7zip with a Scheduled Plex backup.

If I understand, I need to edit PlexBackup.ps1.json like this ?

 **"Type": {
        "_meta": {
            "set": ",7zip,Robocopy",
            "default": "7zip"
        },
        "value": null
    },**

Thank you

**Comment by alekdavis** [comment]
No, no, no. You need to set the `value` element, like:

``` JavaScript
"Type": { "value": "7zip" }
```
The `_meta` element is informational and is not needed by the app. Also, if you installed 7-zip in a non-default folder, set the `ArchiverPath` element (also the `value` property) to point to the proper location of the executable (if it's in the default location, you don't need to do this).

**Comment by Galiwyx** [comment]
Oh thank you, I was not sure yesterday, now it’s clear ! Thank you :)
