### ISSUE TITLE
More "readable" folder name ?

### ISSUE THREAD

**Issue by Galiwyx** [alekdavis/PlexBackup#24]
Hello,

Is it possible to change the name of the folder to a something like this "29-12-2019_15-15-29" ? 

I didn't found any option in the config file. Thank you ! :D

**Comment by alekdavis** [comment]
No, this is not possible. If it were possible, the restore process would not know how to pick up the latest backup folder.

**Comment by Galiwyx** [comment]
It's noted, thank you for your quick response! :)
