### ISSUE TITLE
Is Photo upload supported ?

### ISSUE THREAD

**Issue by Galiwyx** [alekdavis/PlexBackup#25]
Hello,

I have a quick question, is Photo upload supported on the Backup ? https://support.plex.tv/articles/203274057-default-camera-upload-settings/

Thank you !

**Comment by alekdavis** [comment]
I'm not sure what you mean. Unless they are in the folder exclusion list, all folders under Plex Media Server are backed up, so I suspect the answer is "yes".

**Comment by Galiwyx** [comment]
Hello,
Sorry for my bad English, I wanted to know if "%LOCALAPPDATA%\Plex Media Server\Media Upload\Mobile Photos" was backup. I think the answer is yes accorded to you ^^

**Comment by alekdavis** [comment]
That's correct.
