### ISSUE TITLE
Exception calling "Write" with "3" argument(s): "Stream was too long."

### ISSUE THREAD

**Issue by bdrumm1234** [alekdavis/PlexBackup#27]
<pre class="hljs" style="display: block; overflow-x: auto; padding: 0.5em; background: rgb(34, 34, 34); color: rgb(170, 170, 170);">PS C:\WINDOWS\system32&gt; C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\PlexBackup.ps1
PlexBackup v1.<span class="hljs-number" style="color: rgb(0, 204, 102);">6.2</span> (c) <span class="hljs-number" style="color: rgb(0, 204, 102);">2019</span> Alek Davis
Script started at:
  <span class="hljs-number" style="color: rgb(0, 204, 102);">03</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">14</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">2020</span> <span class="hljs-number" style="color: rgb(0, 204, 102);">21</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">56</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">20</span>
Operation mode:
  BACKUP
Backup type:
  DEFAULT
Plex Media Server version (CURRENT):
  <span class="hljs-number" style="color: rgb(0, 204, 102);">1.18</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">8.2527</span>
Stopping Plex service(s):
  Plex Update Service
Stopping Plex Media Server <span class="hljs-keyword" style="color: rgb(102, 68, 170);">process</span>:
  Plex Media Server.exe
Ignoring script parameter:
  ExcludePlexAppDataFiles
Backup will be saved <span class="hljs-keyword" style="color: rgb(102, 68, 170);">in</span>:
  C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">20200314215620</span>
Creating backup folder:
  C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">20200314215620</span>
Creating task-specific subfolder(s) <span class="hljs-keyword" style="color: rgb(102, 68, 170);">in</span>:
  C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">20200314215620</span>
Backing up special subfolders.
Moving folder:
  C:\Users\Blake\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.system\DataItems\Deactivated
to:
  C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">20200314215620</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">3</span>\Plug-in Support\Data\com.plexapp.system\DataItems\Deactivated
at:
  <span class="hljs-number" style="color: rgb(0, 204, 102);">2020</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">03</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">14</span> <span class="hljs-number" style="color: rgb(0, 204, 102);">21</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">56</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">21.437</span>
Completed at:
  <span class="hljs-number" style="color: rgb(0, 204, 102);">2020</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">03</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">14</span> <span class="hljs-number" style="color: rgb(0, 204, 102);">21</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">56</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">21.468</span>
Backing up Plex app <span class="hljs-keyword" style="color: rgb(102, 68, 170);">data</span> folders from:
  C:\Users\Blake\AppData\Local\Plex Media Server
to:
  C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">20200314215620</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">1</span>
Archiving:
  C:\Users\Blake\AppData\Local\Plex Media Server\Cache
to temp file:
  C:\Users\Blake\AppData\Local\Temp\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">6</span>fdf4a99-c09f-<span class="hljs-number" style="color: rgb(0, 204, 102);">4548</span>-b21c-<span class="hljs-number" style="color: rgb(0, 204, 102);">246276</span>f21fb0.zip
at:
  <span class="hljs-number" style="color: rgb(0, 204, 102);">2020</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">03</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">14</span> <span class="hljs-number" style="color: rgb(0, 204, 102);">21</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">56</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">21.533</span>
LogException : Exception calling <span class="hljs-string" style="color: rgb(255, 204, 51);">"Write"</span> with <span class="hljs-string" style="color: rgb(255, 204, 51);">"3"</span> argument(s): <span class="hljs-string" style="color: rgb(255, 204, 51);">"Stream was too long."</span>
At C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\PlexBackup.ps1:<span class="hljs-number" style="color: rgb(0, 204, 102);">2266</span> char:<span class="hljs-number" style="color: rgb(0, 204, 102);">13</span>
+             LogException <span class="hljs-variable" style="color: rgb(187, 17, 102);">$_</span>
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,LogException
 
Restoring special subfolders.
Copying folder:
  C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">20200314215620</span>\<span class="hljs-number" style="color: rgb(0, 204, 102);">3</span>\Plug-in Support\Data\com.plexapp.system\DataItems\Deactivated
to:
  C:\Users\Blake\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.system\DataItems\Deactivated
at:
  <span class="hljs-number" style="color: rgb(0, 204, 102);">2020</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">03</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">14</span> <span class="hljs-number" style="color: rgb(0, 204, 102);">22</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">24</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">41.475</span>
Completed at:
  <span class="hljs-number" style="color: rgb(0, 204, 102);">2020</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">03</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">14</span> <span class="hljs-number" style="color: rgb(0, 204, 102);">22</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">24</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">41.572</span>
Starting Plex service(s):
  Plex Update Service
Starting Plex Media Server <span class="hljs-keyword" style="color: rgb(102, 68, 170);">process</span>:
  C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
Script ended at:
  <span class="hljs-number" style="color: rgb(0, 204, 102);">2020</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">03</span>/<span class="hljs-number" style="color: rgb(0, 204, 102);">14</span> <span class="hljs-number" style="color: rgb(0, 204, 102);">22</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">24</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">42.308</span>
Script ran <span class="hljs-keyword" style="color: rgb(102, 68, 170);">for</span> (hr:min:sec.msec):
  <span class="hljs-number" style="color: rgb(0, 204, 102);">00</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">28</span>:<span class="hljs-number" style="color: rgb(0, 204, 102);">21.911</span>
Script returned:
  ERROR
<span class="hljs-built_in" style="color: rgb(50, 170, 238);">Measure-Object</span> : The property <span class="hljs-string" style="color: rgb(255, 204, 51);">"Length"</span> cannot be found <span class="hljs-keyword" style="color: rgb(102, 68, 170);">in</span> the input <span class="hljs-keyword" style="color: rgb(102, 68, 170);">for</span> any objects.
At C:\PlexBackup-<span class="hljs-number" style="color: rgb(0, 204, 102);">1.6</span>.<span class="hljs-number" style="color: rgb(0, 204, 102);">2</span>\PlexBackup.ps1:<span class="hljs-number" style="color: rgb(0, 204, 102);">3522</span> char:<span class="hljs-number" style="color: rgb(0, 204, 102);">55</span>
+ ... ldItem -Recurse <span class="hljs-variable" style="color: rgb(187, 17, 102);">$BackupDirPath</span> | <span class="hljs-built_in" style="color: rgb(50, 170, 238);">Measure-Object</span> -Property Length -Sum
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Measure-Object], PSArgumentException
    + FullyQualifiedErrorId : GenericMeasurePropertyNotFound,Microsoft.PowerShell.Commands.MeasureObjectCommand
</pre>

Whenever I run the script with the default settings, I get this output. Please assist!

```
PS C:\WINDOWS\system32> Get-Host | Select-Object Version

Version      
-------      
5.1.18362.628

```

**Comment by bdrumm1234** [comment]
I feel like an idiot... If you use: **PlexBackup.ps1 -Robocopy**
It will fix this error.

**Comment by alekdavis** [comment]
You do not need to use the `-Robocopy` flag unless that's what you want. Anyway, if you run into issues, let me know.

**Comment by alekdavis** [comment]
A few things:

1. The _"The property "Length" cannot be found in the input for any objects"_ error is a bug. Well, not really a bug, it only happens if the backup fails. But it's good that you reported it. I will fix it.

2. The _"Exception calling "Write" with "3" argument(s): "Stream was too long""_ error is caused by a Windows API limitation. Most likely it's because one of the files it attempts to archive is over 2 GB, or maybe it has a really long path name. Hard to say which one, but regardless, the default compression mechanism is not as robust as the 7-zip compression, so unless you have a valid reason to use the `-Robocopy` option, I'd recommend using 7-zip.

3. I suspect that your `Cache` folder is really huge. It looks like it took almost 30 minutes to compress the `Cache` folder before it failed, so I would try to see what is wrong with it. See this thread for troubleshooting steps: https://forums.plex.tv/t/how-to-clean-up-the-huge-cache-folder/503871 . There is a chance that you may not need to back up the `Cache` folder at all, in which case you can add it to the list of excluded folders, but see if you can clean it up first and I'm sure that once you do, the backup will be fine.

**Comment by alekdavis** [comment]
Fixed.
