### ISSUE TITLE
What is SubDirFiles?

### ISSUE THREAD

**Issue by EolianPipes** [alekdavis/PlexBackup#28]
Quick question, but what is Sub Folder 1 (SubDirFiles) supposed to include? I just ran my first backup and noticed it was empty. I'm assuming it's looking for files in the root "Plex Media Server" folder as opposed to all the folders that get backed up in Sub Folder 2 (SubDirFolders), but am curious what those would typically be since I don't seem to have any.

Regardless, thank you for writing this awesome script! The Readme and code itself is wonderfully written and commented. Put my little script to shame!

**Comment by alekdavis** [comment]
Hi. Thanks for the feedback. I appreciate it.

Yes, subfolder 1 holds the backup of files in the root Plex Media Server folder
