### ISSUE TITLE
Plex doesn't start after backup

### ISSUE THREAD

**Issue by neoTUGA** [alekdavis/PlexBackup#31]
Hello, 
First of all, great script, does all the backups properly with no problems, great job.

Now to my issue:
After the backup (using robocopy because incremental backups are fast) and script returned SUCCESS it tries to start PMS but "fails". The PMS icon appears in the notification area for a little sometimes during a minute or so, then closes i have to go in and restart it manually. Any ideas?

Also, is there a way to auto close the script on success? It stays running even after the backup has ended.

Thanks for your time.

**Comment by alekdavis** [comment]
First of all, are you running it interactively or as a scheduled task?

Second, what do you mean by "stays running"? Is it stuck on some operation? If so, which one (what is the last log entry you see at the point when it stays running? Or do you mean an open PowerShell window?

About not being able to restart Plex, this is a really weird one. Never seen it and never heard anyone reporting it thus far. Not sure what I can do here. If you are running the script interactively, I'd say: restart it manually. If this is an issue with the scheduled task, consider rebooting the system (there is a switch for this and instructions explaining how to automatically log in and lock the system post reboot).

**Comment by neoTUGA** [comment]
Both, both have exactly the same problem.

Open PowerShell window, so that means that that in the scheduled task it says its running even after it has finished.

The restart "problem" i got working, i started reading the other problems, and reverted the "1808" line and it work, im running a windows domain so it might have been a windows permission thing.
At least now u know :)

**Comment by alekdavis** [comment]
I'm not sure what happened and/or if/how you fixed it, but as long as you are happy, I am happy. :-) Do you still have any issues?

**Comment by neoTUGA** [comment]
Not issue itself, just wondering if there is a way to force close the powershell window after it finished the backup.

**Comment by alekdavis** [comment]
Assuming the script runs to the end, if you are running it as a scheduled task, you can specify it to run without opening PowerShell window (that's what I do, unless I need to troubleshoot something). If you are running it interactively, I am not really sure what your use case is (I assume you want to launch the script, go do your business, and have the script run and exit PowerShell ISE or whatever you are using). If this is the case, I'd ask around PowerShell groups.
