### ISSUE TITLE
Backup error due to missing registery key

### ISSUE THREAD

**Issue by neilmunn** [alekdavis/PlexBackup#34]
I keep getting this error message:

**reg : ERROR: The system was unable to find the specified registry key or value.
At D:\Backup\PlexBackup\PlexBackup.ps1:3115 char:13**

I've looked in regedit the following key doesn't exist:

**"HKU\.DEFAULT\Software\Plex, Inc.\Plex Media Server**

Is the key missing?  And is there a way to remove this error?

**Comment by alekdavis** [comment]
I have no idea what this registry key holds, but according to the more recent Plex articles it needs to be backed up. It does not seem essential to me, though, so the easiest workaround would be to create the key manually. Just leave it empty or put some bogus value in it.

**Comment by alekdavis** [comment]
Hey @neilmunn, any luck?

**Comment by neilmunn** [comment]
Yes, creating an empty key worked fine.  Thanks.
