### ISSUE TITLE
Initialization error.

### ISSUE THREAD

**Issue by clowg** [alekdavis/PlexBackup#39]
Hi.
Just trying to get yr script going today.

I get this error on running it:

![PlexBackup Init Error](https://user-images.githubusercontent.com/20178585/90880546-bc61a100-e3fc-11ea-9d21-7daee4ab3001.png)

I think my troubles may be a restriction caused by the user that runs PMS not being a local administrator and the need to run the ps1 script as an admin.  May be?

**Comment by alekdavis** [comment]
@clowg : Any luck?

**Comment by clowg** [comment]
No sorry.  I could see lots of issues happening with trying to do yr process when the logged on user isnt admin.
I just built a batch file that does what I need, running under the usual logged on user.

Geoff Clow
Snr Solutions Advisor
Datacom
________________________________

**Comment by alekdavis** [comment]
The reason why the script needs to run as an administrator is that it needs to stop Plex services and the PMS process (and then restart them). You cannot do this when running as a non-administrator. Of course, you can stop the services and processes manually then run a script, then start them yourself, so if this works for you, great, but most users, would want the operation to be integrated into one. Anyway, thanks for reporting the bug. I appreciate it.

**Comment by clowg** [comment]
I was able to do this successfully as the non-admin user:

                ECHO  !mytime!: Stopping Tautulli

TASKKILL /IM "Python.exe"

ECHO  !mytime!: Stopping PMS

Taskkill /IM "Plex Media Server.exe"

NET Stop "PlexUpdateService"

**Comment by alekdavis** [comment]
I have no idea how your system is set up but a standard installation does not allow querying, stopping, or starting services, or killing processes as a non-Administrative account:
![NET](https://user-images.githubusercontent.com/2113681/91654111-29a7ae80-ea5b-11ea-9e9f-745e26efe160.PNG)
