### ISSUE TITLE
Script won't backup .bif files when using a 7-zip back up even when I remove .bif from the excluded files in the config file

### ISSUE THREAD

**Issue by bulls23nt** [alekdavis/PlexBackup#40]
Hi,

First let me say thanks for creating this script. It's been very useful. I'm running it the following way:

```
.\PlexBackup.ps1 -SevenZip -NoRestart -Log -ErrorLog -Keep 1
```
And in the config file I made the following edit:

```
"ExcludeFiles": {
        "_meta": {
            "default": ["*.bif"]
        },
        "value": [""]
```

I was hoping that was enough for the bif files to be included in the backup but after examining the backups I see they are not. Perhaps I'm doing something wrong? The config file basically the example config file with that modification. 

I'm attaching the config file as well. (I had to change it from .json to .txt so it would let me attach it)

[PlexBackup.ps1.txt](https://github.com/alekdavis/PlexBackup/files/5224081/PlexBackup.ps1.txt)

**Comment by alekdavis** [comment]
This is weird. It sounds like the default value of the `$ExcludeFiles` parameter is not overwritten by the config file setting. I do not have time to look into it now, but here are some ideas to try:

- Run the script with the `-Verbose` flag and see how the config initialization logic treats the `ExcludeFiles` variable (under the verbose message _Setting variable(s):_). Also check the log entry under the _Excluding file types:_ heading. This won't fix anything but may give some clues.
- Generally, if you want to overwrite a default non-empty/non-null parameter value with an empty/null, value, you need to set the value to `null` in the config file, and set the `hasValue` attribute to `true`. So the config file setting should look like:
```JavaScript
    "ExcludeFiles": {
        "_meta": {
            "default": ["*.bif"]
        },
        "value": $null,
        "hasValue": $true
    }
```
Let me know if it helps.

**Comment by alekdavis** [comment]
@bulls23nt: Sorry, had a couple of typos in the previous comment, so updated the config section:
```JavaScript
    "ExcludeFiles": {
        "_meta": {
            "default": ["*.bif"]
        },
        "value": null,
        "hasValue": true
    }
```

**Comment by alekdavis** [comment]
@bulls23nt : Any luck?

**Comment by bulls23nt** [comment]
@alekdavis sorry for the delayed response I only do the backup about once a week so I was waiting for it to happen. Added the proper syntax for the $ExcludeFiles parameter as you suggested and now the .bif files are backing up. Thank you for your help.

**Comment by alekdavis** [comment]
@bulls23nt Sweet.
