### ISSUE TITLE
Access to the cloud file is denied

### ISSUE THREAD

**Issue by alamoudimoh** [alekdavis/PlexBackup#41]
hi,

i am having my backup folder on my OneDrive folder which is set to always keep offline, however after restoring my backup to a new machine, i starting getting the below error

  C:\Users\xxxx\OneDrive\AppsBackups\Plex\20201115061503
Deleting old backup folder(s):
  20201011061003
Access to the cloud file is denied
  20201004061003
Access to the cloud file is denied
  20200927061003
Access to the cloud file is denied
  20200913061003
Access to the cloud file is denied
  20200906061003

the end of the log seems to be running fine and successfully

Starting Plex Media Server process:
  C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
Script ended at:
  2020.11.15 06:38:43.020
Script ran for (hr:min:sec.msec):
  00:23:39.415
Script returned:
  SUCCESS
Done.

**Comment by alekdavis** [comment]
@alamoudimoh: Are these folders physically exist on you hard drive or are these just shortcuts? If you just restored the backup on a new system, I suspect that they may be just shortcuts (they would get populated with data files once you try to access them). Anyway, if you restored the backup successfully and Plex works without issues, I'd say you do not really need them, so go ahead and manually delete them. If you are not sure if the backup was restored successfully, try validating that the files from at least the latest backup are actually on your hard drive.

**Comment by alamoudimoh** [comment]
> @alamoudimoh: Do these folders physically exist on your hard drive or are these just shortcuts? If you just restored the backup on a new system, I suspect that they may be just shortcuts (they would get populated with data files once you try to access them). Anyway, if you restored the backup successfully and Plex works without issues, I'd say you do not really need them, so go ahead and manually delete them. If you are not sure if the backup was restored successfully, try validating that the files from at least the latest backup are actually on your hard drive.

Thank you,.  They are physically located in the hard drive, and i did restore plex smoothly and everything is fine, before i close this, i would check the coming backup schedule and see how it goes and update you.


My idea is with backups i usually keep them in my onedrive directly for additional layers of backup

**Comment by alekdavis** [comment]
@alamoudimoh What happens if in Windows File Explorer you right click the oldest backup folder (say, 20200906061003) and select the Delete option?

**Comment by alamoudimoh** [comment]
> @alamoudimoh What happens if in Windows File Explorer you right click the oldest backup folder (say, 20200906061003) and select the Delete option?

i can delete them, now i deleted the old files that are causing issues, i will see how it goes with the up coming backup this coming sunday and update you

**Comment by alamoudimoh** [comment]
> @alamoudimoh What happens if in Windows File Explorer you right click the oldest backup folder (say, 20200906061003) and select the Delete option?

Hi,

Deleted the old folder, yet get the same error message.

Question, if the old folders before restoration was in a different path, will this be happening?

I think this only happens to old folders before restoration which have different path

**Comment by alekdavis** [comment]
I'm not sure I understand the question. When you run backup (in the backup mode), it dynamically checks the root backup folder looking for subfolders with the timestamp names, sorts them and removes the oldest one past the threshold. If you do not have any timestamp-named subfolders, the backup will not attempt to delete anything. So I do not understand what is happening there.

**Comment by alamoudimoh** [comment]
alright, since the folders will be somehow there and available for restoration when needed then i will live what the error i have. thank you for your support

**Comment by alamoudimoh** [comment]
found the issue 

https://eazybackup.ca/knowledge-base/error-access-to-the-cloud-file-is-denied-backing-up-onedrive/
