### ISSUE TITLE
Getting a "The term <name> is not 'recognized as the name of a cmdlet, function, script file, or operable program." Error

### ISSUE THREAD

**Issue by SkyEngine-OSP** [alekdavis/PlexBackup#43]
This initially happened on the `Exit-SingleInstance` line but i commented it and now the same happened for `Test-LoggingStarted`. And yes, i tried running on both Administrator mode and not.

![image](https://user-images.githubusercontent.com/12471935/105969733-8a4b1e00-60c3-11eb-937d-9b8bd252f5ae.png)

**Comment by alekdavis** [comment]
Let's step back to the original problem. Go back to the uncommented version. What's the exact error you are getting? The message in the title doesn't have the actual name of the cmdlet called. The way you present it sounds to me like you do not have the required dependencies (or have the older versions of them).

**Comment by SkyEngine-OSP** [comment]
original error message is the same, but points to `Exit-SingleInstance`:
![image](https://user-images.githubusercontent.com/12471935/105974436-dd739f80-60c8-11eb-9109-8473d2ac9e7e.png)



how would i know what dependencies are required? i tried running the command on both Windows Server 2012 R2 and Windows 10 Pro

**Comment by alekdavis** [comment]
Generally, you should not care, because the code is supposed to install all dependencies automatically, which it normally does (this is the first time someone reported this particular problem), but it looks like it did not work on your particular system for some reason. No idea why, unless your system is not connected to the Internet, or has old or corrupted PowerShell, or has some permissions problem. Dependencies are listed on the [README](https://github.com/alekdavis/PlexBackup#dependencies) page. So I would try installing them manually first and see what happens.

**Comment by SkyEngine-OSP** [comment]
hey, thanks for that. managed to get past the dependency errors. was actually almost finished backing up, but then a new error appears during the Metadata archiving part, refer below:

![image](https://user-images.githubusercontent.com/12471935/106344245-526ef100-62e4-11eb-8d65-7271c183d091.png)

i mean i'm already running PowerShell as an Administrator but permission was still denied.

**Comment by alekdavis** [comment]
Not 100% sure, but I suspect that this is due to the limitation of the built-in archiver that cannot handle long paths. There are a couple of ways to handle this, but I would recommend using 7-zip instead of the default archiver. Besides, 7-zip is a lot better in every other respect.

**Comment by SkyEngine-OSP** [comment]
Can confirm that switching to 7zip fixed the issue, and got a lot better compression ratio. This in exchange of loosing the progression tracker on the PowerShell window. But hey, if it works, it works.

i was just a bit lost how to properly configure 7zip as the method basing on the documentation so i added the` -SevenZip` parameter on PowerShell while also setting the default option, not sure sure which worked tho:
![image](https://user-images.githubusercontent.com/12471935/106371393-b48c2c80-639e-11eb-8de5-8f3131533701.png)

either way, it worked. Thank you very much.

**Comment by alekdavis** [comment]
In the config file, it should be:

```
"Type": {
  "value": "7zip"
}.

**Comment by alekdavis** [comment]
I assume this was resolved.
