### ISSUE TITLE
Error: ZipArchiveHelper : Could not find a part of the path

### ISSUE THREAD

**Issue by T1zm1n** [alekdavis/PlexBackup#44]
Hello,

I keep getting the following error in the middle of the backup:
ZipArchiveHelper : Could not find a part of the path 'C:\Users\user\AppData\Local\Plex Media Server\Plex Media Server\Metadata\Albums\1\8f8f782d3066db7ea87a6b0573e065a1e2ad0e9.bundle\Contents\com.plexapp.agents.lyricfind\tracks\1fa14e37789fc5b5f6b5fa1fbfd0fe94eaec21ba\lyrics\c32a0f31a41aa2de43eb84799b25761a29af2d52'.

I can't figure it out.
Thank you.

**Comment by alekdavis** [comment]
Are you using default archiver or 7-zip?

**Comment by T1zm1n** [comment]
I am using the default archiver.

________________________________

**Comment by T1zm1n** [comment]
Hi Alek, I actually just tried it with 7zip and it finished. Sorry about that, I should have tried it before asking.

Thank you for your help.
