### ISSUE TITLE
Plex Update Service not automatically restarting

### ISSUE THREAD

**Issue by admborkbork** [alekdavis/PlexBackup#46]
Running the script with command-line options interactively as follows:
`.\PlexBackup.ps1 -Mode Backup -Type 7zip -PlexAppDataDir 'C:\Program Files (x86)\Plex\Plex Media Server' -BackupRootDir 'F:\Plex-Backup' -Log -ErrorLog -Verbose -Debug`
Backup completes successfully, but the "Plex Update Service" does not automatically restart.

I'm 99.9% sure the issue is on line 1917 of PlexBackup.ps1 --
`if ($services -and ($services.Count -le 0)) {`
should instead read
`if ($services -and ($services.Count -gt 0)) {`

(In other words, if we stopped a service, the .Count should be >0, and thus we should enter the if and restart a service)

Editing that line as above and re-running the script restarts the Plex Update Service after execution correctly.

**Comment by alekdavis** [comment]
@admborkbork Good catch. I updated the script. Please, give it a try.

**Comment by admborkbork** [comment]
Yep, looks great! Thanks!

**Comment by alekdavis** [comment]
@admborkbork Btw, I may be wrong, but I doubt that the Plex app data dir should be at `'C:\Program Files (x86)\Plex\Plex Media Server'`. This is the Plex application (program), not data, folder.

**Comment by admborkbork** [comment]
Hahaha. Fair point. Must have been a copy-paste error when I was writing the bug text (I didn't explicitly copy the actual command-line, but copy-pasted from my .bat file).
