### ISSUE TITLE
Exclude folder don't work properly

### ISSUE THREAD

**Issue by ManuJapan89** [alekdavis/PlexBackup#47]
Hi, i just started using your script
i've edited json config as follow
"ExcludeDirs": {
        "_meta": {
            "default": ["Diagnostics","Crash Reports","Updates","Logs","Cache"]
Basically "Cache" file is not needed as also stated by plex itself so i wanted to exclude it
adding Cache as you can see above

running this command as administrator in powershell... 

PS C:\Users\manue\Downloads\PlexBackup-master\PlexBackup-master> .\PlexBackup.ps1 -Mode Backup -Type 7zip -LogLevel Debug -Log -ErrorLog -Keep 1

it keeps archive the cache folder

json and ps1 have the same name and are in the same folder

also, -loglevel debug don't show anything if i select  -type 7zip
is it normal?
![image](https://user-images.githubusercontent.com/82624098/114958706-de180880-9e63-11eb-8867-07a4f30ab394.png)

**Comment by alekdavis** [comment]
@ManuJapan89 : I'm pretty sure the Cache folder is needed unless you want to redo all poster art, etc. If you feel you do not need it, you need to specify it in the `value` key, not the `default`:

```
"ExcludeDirs": {
        "_meta": {
            "default": ["Diagnostics","Crash Reports","Updates","Logs"]
        },
        "value":  ["Diagnostics","Cache","Crash Reports","Updates","Logs"]
    },
```

The `default` element is just an example of the default.

**Comment by ManuJapan89** [comment]
Thanks you very much... it's an amazing script... in an hour it does with success 30 GB of plex media server... it's unbelievable
