### ISSUE TITLE
Restore Question

### ISSUE THREAD

**Issue by ManuJapan89** [alekdavis/PlexBackup#49]
Hi Mr.Davis, sorry to reach you in this way

i’m running a plex server on a beelink sei8 mini pc, all is working fine except for BSOD like twice a month

Amazon.com: Beelink SEi8 Mini PC 8th Generation Intel i5-8279U Processor,（up to 4.1GHz） Windows 10 Pro Mini Computer with 8G DDR4 RAM/256GB M.2 NVME SSD,Supports 6MB Smart Cache,4K@30Hz Dual HDMI,WIFI6,BT5.0.: Computers & Accessories

with a plex lifetime pass

after many troubleshooting i found out i have a bad block on main ssd(disk c with os and plex files)
chkdsk state no problem on filesystem but there are 32kb of files on damaged sectors
no matter how many times i run chkdsk /f /r at boot

Damaged sector is on the primary boot partition on a first sight

even if i’m not completely sure the ssd is the problem, i have intention to replace it soon with another ssd nvme to exclude it’s the real problem.

Since the very beginning i’ve done backup with your script but never done a restore

The correct step to restore, just to be sure are:

Reinstall os from 0

-install everything i need other than plex and update os and driver, then:

i don’t know if i have first to download and install plex media server and login in or if i have first to restore plex files using the script with a command like this:

.\PlexBackup.ps1 -Mode Restore -BackupDirPath “\MYNAS\PlexBackup\20190101183015”

andf only after install plex media server and login again?

Which one is correct? It’s very important to me because i’ve very huge libraries, if i have to restart from 0 it’ll take 2 weeks at least working on it with 2 people

Obviously the media content drive will be placed in the same location as they were before, i mean drive letter and other stuff…
(Media content are something like 10 TB splitted on 4 external hdds WD, connected to mini pc by a powered HUB usb 3.0)

in restore mode i have to specify to use 7zip? if yes,which command i have to use?

Thanks for your answer

Best Regards

**Comment by alekdavis** [comment]
@ManuJapan89 : First, you install OS and all drivers. Make sure everything works. Then install Plex Media Server (preferably the same version you used for the last backup). Once you install Plex, run the restore. If you used 7zip for backups, you should specify the switch for restores (unless it is already set in the config file). You do not need to specify the path to the backup folder if your backup root is defined in the config file and you use the standard naming convention for the backup folder names (the script will pick up the folder with the latest name). Assuming that your media files are at the same locations, that should do it.

**Comment by ManuJapan89** [comment]
Hi,
thanks for your reply
usually i run plexbackup directly on this path C:\Users\manue\Downloads\PlexBackup-master\PlexBackup-master
in a powershell run as admin i type cd C:\Users\manue\Downloads\PlexBackup-master\PlexBackup-master
then run a backup using the following: .\PlexBackup.ps1 -Mode Backup -Type 7zip -LogLevel Debug -Log -ErrorLog -Keep 1
The folder created as backup will then moved on a external hdd attached to the mini pc
If i move the backup folder back to original loaction e.g(C:\Users\manue\Downloads\PlexBackup-master\PlexBackup-master\20210812202129)
Can i run the restore using the following command?
.\PlexBackup.ps1 -Mode Restore -Type 7zip -LogLevel Debug -Log -ErrorLog -NoRestart
or i have to specify always the backup dir?

looking into this option BackupDirPath

When running the script in the Restore mode, holds path to the backup folder (by default, the subfolder with the most recent timestamp in the name located in the backup root folder will be used).

there's no need to specify

If i have to i was thinking about this: .\PlexBackup.ps1 -Mode Restore -Type 7zip -BackupDirPath "C:\Users\manue\Downloads\PlexBackup-master\PlexBackup-master\20210812202129" -LogLevel Debug -Log -ErrorLog -NoRestart

**Comment by alekdavis** [comment]
@ManuJapan89 : First, I'd recommend keeping the command-line option that do not change (like the type of backup, i.e. 7zip) in the config file (to reduce typing or execution errors). Second, if your backup process creates a local backup (using the default folder) and then you manually copy the files to an external drive, I'm not sure why you wouldn't just point to the external drive. Why use an extra manual step if the backup can do it for you? But regardless, if you do not mess with the backup folder names, the only thing the script needs to know is the root backup folder (under which the timestamped subfolders get created, so normally, you do not need to specify the BackupDirPath, as long as you have BackupRootDir defined (but you have an option to use BackupDirPath on the restore operation , if you want).
