### ISSUE TITLE
confused about TempZipFileDir

### ISSUE THREAD

**Issue by Zixim** [alekdavis/PlexBackup#5]
If this is in the config file ( `PlexBackup.ps1.json` ) : 
```
    "TempZipFileDir": {
        "hasValue": true,
        "value": null
```
then does the compression staging happen in windows `TEMP` folder ?

**Comment by alekdavis** [comment]
No, this means: do not use the staging folder and compress directly in the backup directory. To compress fitting in the staging TEMP folder, remove the hasVaue atrribute.

**Comment by alekdavis** [comment]
Does this make sense?

**Comment by Zixim** [comment]
I don't want to have a temp file during the compression. 
So the default setting in the configuration file is what i want : 

Compress directly to `BackupRootDir`  : 
```
"TempZipFileDir": {
        "hasValue": true,
        "value": null
},
```
For posterity : 
In case some one wants to use a temporary compression file in Windows temp, what would the config look like ?
What about if the staging needs to happen in `D:\some_temp_folder\`  ?

**Comment by alekdavis** [comment]
If you want to stage compression to the temp directory, use:
```JavaScript
'TempZipFileDir' : { 'value' : null }
```
If staging needs to happen in some temp folder, use:
```JavaScript
'TempZipFileDir' : { 'value' : 'D:\\some_temp_folder' }
```

**Comment by Zixim** [comment]
erm...back to confused...

use windows temp : `'TempZipFileDir' : { 'value' : null }`
use specific folder : `'TempZipFileDir' : { 'value' : 'D:\\some_temp_folder\\'}`
don't use any staging : ???

**Comment by alekdavis** [comment]
You just posted the example of not using staging and it is absolutely correct.

**Comment by Zixim** [comment]
whats the difference between 
`'TempZipFileDir' : { 'value' : null }`
and
```
"TempZipFileDir": {
        "hasValue": true,
        "value": null
}
```

**Comment by alekdavis** [comment]
By default, if the value of a property in the config file is null/empty string/false/0 (i. e. if it is evaluated to $false by PowerShell, sure as `if (!$value)`), the script will not use if (it will assume that the value is not specified), so the default value or the value specified via command line will be used. But if you set the `hasValue` property to `true`, the script will use it even if it evaluated to `$false`. Makes sense?
