### ISSUE TITLE
Error compressing Plex app data files. Error compressing folder 'Cache'. Exception calling "Write" with "3" argument(s): "Stream was too long." Stream was too long.

### ISSUE THREAD

**Issue by Pottypotsworth** [alekdavis/PlexBackup#50]
Hi there,

I have just installed the script and set everything up. On first backup run the backup seemed to finish really quick, so I went to the PlexBackup destination folder and opened the Backup.log. The script seems to have failed with the error of "Error compressing Plex app data files. Error compressing folder 'Cache'. Exception calling "Write" with "3" argument(s): "Stream was too long." Stream was too long."

I searched this on Google but didn't get any results.

My entire log is below, any ideas how to resolve this? Thanks

```
PlexBackup v2.0.6 (c) 2019-2021 Alek Davis
Script started at:
  09/08/2021 16:32:58
Operation mode:
  BACKUP
Backup type:
  DEFAULT
Plex version:
  1.24.2.5000
Log file:
  B:\PlexBackup\20210908163258\Backup.log
Stopping Plex services:
  Plex Update Service
Stopping Plex Media Server process:
  Plex Media Server.exe
Backup will be saved in:
  B:\PlexBackup\20210908163258
Creating task-specific subfolders in:
  B:\PlexBackup\20210908163258
    1
    2
    3
    4
Saving version:
  1.24.2.5000
to:
  B:\PlexBackup\20210908163258\Version.txt
Backing up special folders.
Moving:
  C:\Users\Chewie\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.system\DataItems\Deactivated
to:
  B:\PlexBackup\20210908163258\4\Plug-in Support\Data\com.plexapp.system\DataItems\Deactivated
at:
  2021/09/08 16:33:02.604
Completed at:
  2021/09/08 16:33:02.700
Backing up Plex app data files in the root folder.
No files found in 'C:\Users\Chewie\AppData\Local\Plex Media Server' (it's okay).
Backing up Plex app data folders.
Archiving:
  C:\Users\Chewie\AppData\Local\Plex Media Server\Cache
to:
  B:\PlexBackup\20210908163258\2\Cache.zip
at:
  2021/09/08 16:33:03.210
Restoring special folders.
Copying:
  B:\PlexBackup\20210908163258\4\Plug-in Support\Data\com.plexapp.system\DataItems\Deactivated
to:
  C:\Users\Chewie\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.system\DataItems\Deactivated
at:
  2021/09/08 16:39:42.219
Completed at:
  2021/09/08 16:39:42.274
Error compressing Plex app data files. Error compressing folder 'Cache'. Exception calling "Write" with "3" argument(s): "Stream was too long." Stream was too long.
Starting Plex services:
  Plex Update Service
Starting Plex Media Server:
  C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
Script ended at:
  09/08/2021 16:39:42
Script ran for (hr:min:sec.msec):
  00:06:43.795
Script execution result:
  ERROR
Done.
```

**Comment by alekdavis** [comment]
@Pottypotsworth Please, see https://github.com/alekdavis/PlexBackup/issues/27

**Comment by Pottypotsworth** [comment]
Thanks @alekdavis - in that thread you stated...

> > A few things:
> 
>     The "The property "Length" cannot be found in the input for any objects" error is a bug. Well, not really a bug, it only happens if the backup fails. But it's good that you reported it. I will fix it (https://stackoverflow.com/questions/43308663/measure-object-the-property-length-cannot-be-found-in-the-input-for-any-obje).
> 
>     The "Exception calling "Write" with "3" argument(s): "Stream was too long"" error is caused by a Windows API limitation. Most likely it's because one of the files it attempts to archive is over 2 GB, or maybe it has a really long path name. Hard to say which one, but regardless, the default compression mechanism is not as robust as the 7-zip compression, so unless you have a valid reason to use the -Robocopy option, I'd recommend using 7-zip.
> 
>     I suspect that your Cache folder is really huge. It looks like it took almost 30 minutes to compress the Cache folder before it failed, so I would try to see what is wrong with it. See this thread for troubleshooting steps: https://forums.plex.tv/t/how-to-clean-up-the-huge-cache-folder/503871 . There is a chance that you may not need to back up the Cache folder at all, in which case you can add it to the list of excluded folders, but see if you can clean it up first and I'm sure that once you do, the backup will be fine.


For me...

1) I guess this "bug" is already fixed?
2) I am using 7Zip so there should be no issue?
3) My Cache folder is only 27GB which seems relatively small compared to others.

I am not sure how to proceed, other than perhaps I should try Robocopy?

Thanks

**Comment by alekdavis** [comment]
@Pottypotsworth Yes, (1) is irrelevant. For (2), based on your log file, you are not using 7-zip:

```
Script started at:
  09/08/2021 16:32:58
Operation mode:
  BACKUP
Backup type:
  DEFAULT
```

(3) is your choice. It's not terribly bad if you do not mind 10 or so minutes spent on backing it up.

The key thing is make sure you run the script with the `-SevenZip` option.

**Comment by Pottypotsworth** [comment]
Thanks @alekdavis - I set 7-zip as the default in the .json so didn't realise I also needed to use the -SevenZip option.

The process seems to be running for much longer this time. I'll let it run over night and report back tomorrow on the success and if we can close this issue :)

**Comment by alekdavis** [comment]
@Pottypotsworth If you set it in config (JSON) file, you do not need to specify it on command line. I suspect your JSON setting is not correct. Make sure it is defined as:

```
"Type": {
        "value": "7zip"
    },
```

**Comment by Pottypotsworth** [comment]
> @Pottypotsworth If you set it in config (JSON) file, you do not need to specify it on command line. I suspect your JSON setting is not correct. Make sure it is defined as:
> 
> ```
> "Type": {
>         "value": "7zip"
>     },
> ```

Yeah, i think I had it slightly wrong. Sorry to be off topic, but whilst I have you. Is it possible to set the max number of backups in the JSON as opposed to an argument when running from the Powershell?

So only ever keep the recent backup + the previous backup?
