### ISSUE TITLE
Add winrar support

### ISSUE THREAD

**Issue by jimger** [alekdavis/PlexBackup#55]
Can you also add winrar support? Not sure how it is benchmarked against 7zip but wouldn't be bad...

**Comment by alekdavis** [comment]
I frankly don't see the point. It would add a lot more complexity (one extra compression type, new command-line arguments, etc) and for what? There would need to be a really compelling case to do this and at this point, I don't see one. 7zip is free, fast, and efficient. Using RAR would give marginal improvements at best and come at the cost of increased complexity. That's not a good ROI in my book.
