### ISSUE TITLE
Failed to send email notification (SendGrid)

### ISSUE THREAD

**Issue by MrPeanut12** [alekdavis/PlexBackup#56]
I'm trying to set up email notifications through SendGrid. I've updated my config file with the options below (relevant parts). I generated my credential file using the command in the readme. I've tested the SMTP connection outside of this script and it works as expected. However, I'm getting this error from the script.

Is there anything else I can do to help debug this error?

> Failed to send email notification.
> The process cannot access the file 'C:\Users\User\Desktop\20220214095622\Backup.log' because it is being used by another process.

```json
    "SendMail": {
        "value": "Always"
    },
    "SmtpServer": {
        "value": "smtp.sendgrid.net"
    },
    "Port": {
        "value": 587
    },
    "From": {
        "value": "plex@mydomain.com"
    },
    "To": {
        "value": "myemail@gmail.com"
    },
    "NoSsl": {
        "value": null
    },
    "CredentialFile": {
        "value": "C:\\Users\\User\\Documents\\PlexBackup.ps1.xml"
    },
```

**Comment by MrPeanut12** [comment]
My mistake -- I did have the `SendLogFile` property set to `Always`. I've changed this to `Never` and the email is now working. Turns out it wasn't related to SendGrid at all. Thanks for the help!

One quick question since it's not worth opening a new issue for... Is this the expected result of the script? (For some reason, I was expecting a single 7-zip file.)

- YYYYMMDDHHMMSS
  - 1
    - Plex.7z
  - 2
    - Cache.7z
    - Codecs.7z
    - Media.7z
    - Metadata.7z
    - Plug-in Support.7z
    - Plug-ins.7z
  - 3
    - *.reg
  - 4
    - Plug-in Support\Data\{...}
  - Backup.log
  - Version.txt

**Comment by alekdavis** [comment]
Yes, that's by design. The archived files are often huge, so splitting them into separate files helps with transfer (I hope you do not save them on the desktop, right?).

**Comment by MrPeanut12** [comment]
Great, thank you. I am still setting it up, but plan to save to my NAS. Thanks for your help on this.
