### ISSUE TITLE
Plex not running doesnt email Error

### ISSUE THREAD

**Issue by snupple** [alekdavis/PlexBackup#62]
If Plex server is not running I can see a red error message in the console, but there is no Error Log created and I recieve a SUCCESS email, should this not be a ERROR email with an error log attached?   (Unless "InActive flag is set)

**Comment by alekdavis** [comment]
Can you share the log?

**Comment by snupple** [comment]
There nis no log created,  but here is the console output:
![2022-06-29_18h57_18](https://user-images.githubusercontent.com/851790/176420795-e8f6e7d4-7928-4fc6-aef6-c42f037dbe77.png)

and the email

![2022-06-29_18h59_01](https://user-images.githubusercontent.com/851790/176420892-b60d786d-3274-4953-aa61-c91672db85d2.png)

**Comment by alekdavis** [comment]
The log is not created because initialization logic has not completed. So it's expected. But the email is obviously wrong. I checked in what I think would fix the email issue, but I cannot test it right now. Please give it a try and let me know if it generates the correct email.

**Comment by snupple** [comment]
Uh oh, so I get a email when the Plex Server is not running but when everythin works fine I don't get a email
[Backup.log](https://github.com/alekdavis/PlexBackup/files/9034609/Backup.log)

**Comment by alekdavis** [comment]
Could you share your command line and config file?

**Comment by snupple** [comment]
Sure:

`powershell.exe -noprofile -executionpolicy bypass -file .\PlexBackup.ps1 -ConfigFile .\PlexBackup.ps1.json`

`{
    "_meta": {
        "version": "1.0",
        "strict": false,
        "description": "Sample run-time settings for the PlexBackup.ps1 script."
    },
    "Mode": {
        "_meta": {
            "set": "Backup,Continue,Restore",
            "default": "Backup"
        },
        "value": null
    },
    "Type": {
        "_meta": {
            "set": ",7zip,Robocopy",
            "default": ""
        },
        "value": null
    },
    "PlexAppDataDir": {
        "_meta": {
            "default": "$env:LOCALAPPDATA\\Plex Media Server"
        },
        "value": null
    },
    "BackupRootDir": {
        "_meta": {
            "default": "$PSScriptRoot"
        },
        "value": "C:\\Plex\\Plex Backup"
    },
    "BackupDir": {
        "_meta": {
            "default": null
        },
        "value": null
    },
    "TempDir": {
        "_meta": {
            "default": "$env:TEMP"
        },
        "hasValue": true,
        "value": null
    },
    "WakeUpDir": {
        "_meta": {
            "default": null
        },
        "value": null
    },
    "ArchiverPath": {
        "_meta": {
            "default": "$env:ProgramFiles\\7-Zip\\7z.exe"
        },
        "value": null
    },
    "Quiet": {
        "value": null
    },
    "LogLevel": {
        "_meta": {
            "default": "None,Error,Warning,Info,Debug"
        },
        "value": "Debug"
    },
    "Log": {
        "value": true
    },
    "LogFile": {
        "value": null
    },
    "ErrorLog": {
        "value": true
    },
    "ErrorLogFile": {
        "value": null
    },
    "Keep": {
        "_meta": {
            "range": "0-[int]::MaxValue",
            "default": "7"
        },
        "value": 3
    },
    "Retries": {
        "_meta": {
            "range": "0-[int]::MaxValue",
            "default": "5"
        },
        "value": null
    },
    "RetryWaitSec": {
        "_meta": {
            "range": "0-[int]::MaxValue",
            "default": "10"
        },
        "value": null
    },
    "RawOutput": {
        "value": null
    },
    "Inactive": {
        "value": null
    },
    "NoRestart": {
        "value": null
    },
    "NoSingleton": {
        "value": null
    },
    "NoVersion": {
        "value": null
    },
    "NoLogo": {
        "value": null
    },
    "Test": {
        "value": false
    },
    "SendMail": {
        "_meta": {
            "set": "Never,Always,OnError,OnSuccess,OnBackup,OnBackupError,OnBackupSuccess,OnRestore,OnRestoreError,OnRestoreSuccess",
            "default": "Never"
        },
        "value": "Always"
    },
    "SmtpServer": {
        "value": "mail.REDACTED.lol"
    },
    "Port": {
        "_meta": {
            "range": "0-[int]::MaxValue",
            "default": "0"
        },
        "value": 587
    },
    "From": {
        "value": "rick@REDACTED.lol"
    },
    "To": {
        "value": "rick@REDACTED.lol"
    },
    "NoSsl": {
        "value": false
    },
    "CredentialFile": {
        "value": null
    },
    "NoCredential": {
        "value": null
    },
    "Anonymous": {
        "value": null
    },
    "SendLogFile": {
        "_meta": {
            "set": "Never,OnError,OnSuccess,Always",
            "default": "Never"
        },
        "value": "Always"
    },
    "Logoff": {
        "value": null
    },
    "Reboot": {
        "value": null
    },
    "ForceReboot": {
        "value": null
    },
    "ExcludeDirs": {
        "_meta": {
            "default": ["Diagnostics","Crash Reports","Updates","Logs"]
        },
        "value": null
    },
    "ExcludeFiles": {
        "_meta": {
            "default": ["*.bif"]
        },
        "value": null
    },
    "SpecialDirs": {
        "_meta": {
            "default": ["Plug-in Support\\Data\\com.plexapp.system\\DataItems\\Deactivated"]
        },
        "value": null
    },
    "PlexServiceName": {
        "_meta": {
            "default": "^Plex"
        },
        "hasValue": false,
        "value": null
    },
    "PlexServerFileName": {
        "_meta": {
            "default": "Plex Media Server.exe"
        },
        "value": null
    },
    "PlexServerPath": {
        "value": null
    },
    "ArchiverOptionsCompress": {
        "_meta": {
            "comment": "The default options will always be applied. To include additional options, define them as an array.",
            "default": ["-r","-y"]
        },
        "value": null
    },
    "ArchiverOptionsExpand": {
        "_meta": {
            "comment": "The default options will always be applied. To include additional options, define them as an array.",
            "default":  ["-aoa","-y"]
        },
        "value": null
    }
}`

**Comment by alekdavis** [comment]
Hmmm... Don't know what to make of it. I have been running the latest script version for a few days and I get the mail delivered fine. You config file looks normal. Could it have been sent to the Spam folder?

**Comment by snupple** [comment]
Doing some more testing and I noticed something odd.. When the backup is successful  right at the end of the process there is the red word "rocess."

![2022-07-05_10h20_32](https://user-images.githubusercontent.com/851790/177238545-567da85e-5d80-4622-9592-5680fb05f65b.png)

**Comment by alekdavis** [comment]
It doesn't seem to be successful. I do not see any log  messages. Try running it with the -Verbose flag.

**Comment by snupple** [comment]
aha!

![image](https://user-images.githubusercontent.com/851790/177241384-c4c37d55-1f23-4156-b3fa-a6d156970e3f.png)

**Comment by alekdavis** [comment]
Could you share the full output?

**Comment by snupple** [comment]
Here we are

[PlexBackup.zip](https://github.com/alekdavis/PlexBackup/files/9043938/PlexBackup.zip)

**Comment by alekdavis** [comment]
Also need the log file.

**Comment by alekdavis** [comment]
Run it with switch:

```
*> plexbackup.log
```
This redirect all output streams (success, error, verbose) to the plexbackup.log (include full path if needed).

**Comment by alekdavis** [comment]
Or use https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-7.2

**Comment by snupple** [comment]
Here we go

[PowerShell_transcript.TOSHIBA-I5.IFaLedr4.20220705203745.txt](https://github.com/alekdavis/PlexBackup/files/9046467/PowerShell_transcript.TOSHIBA-I5.IFaLedr4.20220705203745.txt)

**Comment by alekdavis** [comment]
This is weird. When I used Start-Transcript, it saved all messages from the console (output, verbose, errors, etc). Your file only has verbose messages.

**Comment by alekdavis** [comment]
I have another issue opened on this, so I will look into it  a bit more closely.

**Comment by alekdavis** [comment]
Okay, I think it should be fixed now. Let me know.

**Comment by snupple** [comment]
Yes, All good now - thanks for your prompt response!

**Comment by alekdavis** [comment]
Thanks for reporting it.
