### ISSUE TITLE
With Log set to true, no email and error

### ISSUE THREAD

**Issue by pearlset79** [alekdavis/PlexBackup#63]
Hello, the script is working really well for me except for one thing.  If I have Send Email value set to Always and have the Log set to true, I get an error at the end of the script running saying it could not email because file is in use.  The script does create a log.  If Log is set to null, I do not get a log file, but get an email saying "Success".  Is there a way to have a log and an email?

**Comment by alekdavis** [comment]
Should be fixed. Let me know.

**Comment by pearlset79** [comment]
I ran the script and it created the log file but still no email.  The log says "success" with no email errors.  I have SendMail set to "Always" and Log set to true.  Am I doing something wrong?  Other 2 log options are set to null.

**Comment by alekdavis** [comment]
Please run the backup script within the Start-Transcript block (see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-7.2) and `-Verbose -Debug` switches, e.g.:

```
Start-Transcript -Path "c:\logs\transcript.txt"
.\Plexbackup.ps1 ... -Verbose -Debug
Stop-Transcript

Then post the transcript file. I will take a look.

**Comment by alekdavis** [comment]
I do not see the transcript file, but first of all, did you try the latest version of the script?

**Comment by pearlset79** [comment]
It would seem after getting the new script and making some small changes all is well....thanks for the script and support!
