### ISSUE TITLE
PlexBackup.ps1 is not digitally signed

### ISSUE THREAD

**Issue by Bboy486** [alekdavis/PlexBackup#66]
PS C:\WINDOWS\system32> cd C:\Users\User\Downloads
PS C:\Users\User\Downloads> .\PlexBackup.ps1
.\PlexBackup.ps1 : File C:\Users\User\Downloads\PlexBackup.ps1 cannot be loaded. The file
C:\Users\User\Downloads\PlexBackup.ps1 is not digitally signed. You cannot run this script on the current system. For
more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\PlexBackup.ps1
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by alekdavis** [comment]
Have you tried following the instructions: https://github.com/alekdavis/PlexBackup/blob/master/README.md#script-execution ?
