### ISSUE TITLE
error on Win8 machine

### ISSUE THREAD

**Issue by Zixim** [alekdavis/PlexBackup#7]
reporting this even though it should have no future impact, and it is a marginal usage case..
Setting up backup on a family member's windows 8.1 machine, I got this error : 

```
Compress-Archive : The term 'Compress-Archive' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At C:\users\edited\Downloads\PlexBackup-master\PlexBackup.ps1:2259 char:17
+                 Compress-Archive -DestinationPath $zipFilePath -Update
+                 ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Compress-Archive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

The error is pretty obvious, and the core reason is certainly the not-updated W8 OS.
Since I'll be using Robocopy, this is of no further consequence to me.
Perhaps some more elegant way of intercepting the missing Compress-Archive function is worth investigating...?

**Comment by alekdavis** [comment]
The real question is why in 2019 anyone would be using Windows 8. ;-) I'm not going to do anything here.
