### ISSUE TITLE
issue with backup

### ISSUE THREAD

**Issue by david-corkill** [alekdavis/PlexBackup#70]
When I run the script, it creates a file called $zipFilePath.zip in the folder where by backup script is located. I also notice that the folder '1' in the destination is empty. I am assuming this file should be in that path

if I open $zipFilePath.zip, it contains the following

.LocalAdminToken
plexmediaserver.pid
Preferences.xml
Setup Plex.html

If I create a logfile, it gives this logging info for that step

Saving version:
  1.30.0.6486
to:
  \\NAS\Backup\Plex\20221219075615\Version.txt
Backing up Plex app data files in the root folder.
No files found in 'C:\Users\Administrator\AppData\Local\Plex Media Server' (it's okay).

**Comment by david-corkill** [comment]
Just to add a note, it appears to be if I use parameters in the bat file rather than the json. The json works correctly, never mind me

**Comment by alekdavis** [comment]
So, are you good or do you need help?

**Comment by david-corkill** [comment]
I am good. If it is meant to work with parameters in place of the config file, it might have a problem, but config file worked as expected.

**Comment by alekdavis** [comment]
It works with parameters and config file (including using both in the same call, in which case command line parameters tace precedence). I'm just not sure what you did originally. Like where is the batch file coming from? There should be no batch files. You can use config file in the japn or in format, but I don't know how you pass parameters via a batch file.

**Comment by david-corkill** [comment]
I worked out what caused it, it is because there is no default for 'Type' set in the json. 

If the backup command is run without that parameter configured or the edited added to the .json, it creates a zip called $zipFilePath.zip in the directory where the script is run instead of putting it in the 1 directory in the backup path.

it is only the 1 directory (files) that acts weird. If Type isnt configured, the other folders are correctly zipped.
