### ISSUE TITLE
Can't start Plex after backup

### ISSUE THREAD

**Issue by semisane** [alekdavis/PlexBackup#73]
I'm receieving the message: 
RUNAS ERROR: Unable to run - C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe
87: The parameter is incorrect.

I've changed the plex directory in the PowerShell file to remove the Program Files (x86) folder since Plex is installed in Program Files. 

No matter what I change in the PowerShell or JSON file I receive the same message after a backup.
Before the backup begins, if Plex is not running, I will receieve an error message. 

Not sure if this is a permissions issue or?
Any help would be appreciated.

**Comment by alekdavis** [comment]
I'm not quite following. Why are you trying to launch backup with Plex Media Server (PMS) not running? Let's ignore this case for now. If you launch it normally (with PMS running), does backup complete and you get the error when it tries to restart PMS? If this is the case, it looks like an OS issue. I think someone already posted something similar a while ago. When I get to my computer, I will try to find that thread or you can try searching yourself.

**Comment by semisane** [comment]
I ran the backup script with Plex running. It threw the error above after creating the backups. I tried to run it again, forgetting that the script closes Plex. I restarted Plex and ran it again. Received the same error. 

When I run the script it creates all backups successfully. It does NOT restart the Plex Media Server.

If you have that info handy, when you get back to your computer, I'd greatly appreciate it. I'll keep looking but haven't found much help.

Thanks in advance!

**Comment by alekdavis** [comment]
Please check this thread: https://github.com/alekdavis/PlexBackup/issues/67

**Comment by semisane** [comment]
After the runas changes, testing now. Will follow up. 
If this is an issue in W11 would it be possible to include a commented out line or FAQ that folks could review? I know that it was also set as Program Files (x86) which, I believe, needed to be changed.

**Comment by semisane** [comment]
That did in fact work - thanks for the help. Much appreciated!

**Comment by alekdavis** [comment]
Added a workaround in https://github.com/alekdavis/PlexBackup/releases/tag/v2.1.7.
