### ISSUE TITLE
After backup completes getting an error when the script attempts to start Plex

### ISSUE THREAD

**Issue by rock7632** [alekdavis/PlexBackup#74]
First of all great work. The script works really well but the one issue I'm having is that once the backup completes, the script attempts to start Plex but gives the following error:

`RUNAS ERROR: Unable to run - C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe
87: The parameter is incorrect.`

This is preventing me from running it as a scheduled task. Any help would be appreciated. Thank you

**Comment by alekdavis** [comment]
Please see the thread https://github.com/alekdavis/PlexBackup/issues/67

**Comment by rock7632** [comment]
> Please see the thread #67

Thanks. I will try that.

**Comment by alekdavis** [comment]
Added a workaround in https://github.com/alekdavis/PlexBackup/releases/tag/v2.1.7.
