### ISSUE TITLE
Plex Media Server Not Restarting

### ISSUE THREAD

**Issue by pearlset79** [alekdavis/PlexBackup#75]
Hello, just started having an issue.  Everything backs up as it should and I get an email saying "success".  The issue is that PMS does not start after the backup is complete.  I do not see anything saying there is an error.  Thanks for the help and letting me know if you are in need of more information.  -Nick

**Comment by alekdavis** [comment]
Please see https://github.com/alekdavis/PlexBackup/issues/67
