### ISSUE TITLE
Email Notification Not Working

### ISSUE THREAD

**Issue by pearlset79** [alekdavis/PlexBackup#76]
All was working well and I was getting an email alert each time, but not now.  I used the script to create an xml file from a Google App password.  The script seems to point to that xml file, but when the script runs it always prompts me for my Gmail username and password.  I'm sure this is something simple.

**Comment by alekdavis** [comment]
This means that either the file is not there or the script does not have rights to read it. Can you actually open the file? For example, if the file is in the OneDrive folder, it may not actually be on the local file system (it only contains a link to the file which must be downloaded from the cloud).

**Comment by pearlset79** [comment]
Sorry, I missed the minor issue when I posted this.  You can go ahead and mark this solved :-)
