### ISSUE TITLE
Plex Backup Failing-Nothing Changed

### ISSUE THREAD

**Issue by pearlset79** [alekdavis/PlexBackup#77]
Hello, my plex backup has been working fine and all of a sudden without anything changing, it now fails.  I will attach the log file to see if you can find what is wrong.
[Backup.log](https://github.com/alekdavis/PlexBackup/files/11929360/Backup.log)

**Comment by alekdavis** [comment]
It looks like it fails to archive the `Media` folder. Try running the script with these flags: `-Debug -Verbose -RawOutput`. It should give you the error from `7zip`.

**Comment by pearlset79** [comment]
Pardon me for asking for clarity, but do all 3 of those go under Log Level or somewhere else?  Thanks!

**Comment by alekdavis** [comment]
I'm not sure what you mean. Just append these switches to the command line options that you normally use.

**Comment by pearlset79** [comment]
In the json file itself or the command line in powershell?  Sorry I’m still learning some of this.

**Comment by alekdavis** [comment]
On command line. Leave everything as-is.

**Comment by pearlset79** [comment]
OK, so I get success if I run it with -Debug -Verbose -RawOutput.  What does that mean?

**Comment by alekdavis** [comment]
No idea, but I suspect that it should work if you run it normally.

**Comment by pearlset79** [comment]
It does not

**Comment by alekdavis** [comment]
Hmm.... Need yo think about it. There should be no difference in functionality.

**Comment by alekdavis** [comment]
I think I had a bug which caused the suppression of the 7zip error. I'm expecting to see an error like `7-zip returned` followed by a number, but I do not see it. I made a minor change hoping to get the error. Could you get the latest version of the PlexBackup.ps1 script and try it again (I'd need the log file or the error message containing the `7-zip returned` error if it gets logged)?

**Comment by pearlset79** [comment]
It appears 7zip is having trouble zipping the "Media" folder for some reason.
[Backup.log](https://github.com/alekdavis/PlexBackup/files/11949695/Backup.log)

**Comment by alekdavis** [comment]
This part I do know. The question is why. It looks like your last log file is still from the 2.1.4 version of the script. The latest version is 2.1.6, so please try it. Just download the PlexBackup.ps1 file (do not get the latest release, because I did not create a new release for the new update).

**Comment by pearlset79** [comment]
I’m sorry, but how do I update again?  I appreciate all your help!

**Comment by alekdavis** [comment]
Go here and click the button to download this file: https://github.com/alekdavis/PlexBackup/blob/master/PlexBackup.ps1

**Comment by alekdavis** [comment]
Any luck?

**Comment by pearlset79** [comment]
I found there was a corrupted file with subtitles.  I deleted the file which did not impact anything and all is well.  I do need to upgrade and will do that this weekend when I have some time.  Thanks for your assistance!
