### ISSUE TITLE
RUNAS ERROR: Unable to run ... 87: The parameter is incorrect.

### ISSUE THREAD

**Issue by ktimb** [alekdavis/PlexBackup#82]
`RUNAS ERROR: Unable to run - C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe
87: The parameter is incorrect.`

Hi after moving to Powershell 5, my backup went smoothly then I was able to restore to my new computer with no issues. Thanks!

However when I ran a backup on the new computer I got the above error. I confirmed that `C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe` is the correct location of the .exe.

The backup was created with no issue, but the server wasn't restarted. Thanks for any help in advance.

**Comment by alekdavis** [comment]
Please see https://github.com/alekdavis/PlexBackup/issues/67.

**Comment by alekdavis** [comment]
Added a workaround: https://github.com/alekdavis/PlexBackup/releases/tag/v2.1.7.
