### ISSUE TITLE
Plex Backup Fails Through Task Scheduler (Win 10 Pro)

### ISSUE THREAD

**Issue by pearlset79** [alekdavis/PlexBackup#83]
Plex Backup fails when run at scheduled time on Windows 10 Pro Task Scheduler, but when run manually everything is fine.  Nothing as changed on the server, it just started failing.  It appears to start and then shoots the email stating that it failed immediately after starting.

**Comment by alekdavis** [comment]
@pearlset79 There isn't much info in the description to go by. What is the exact error message? Did the log file get created? If so, what is in the log file? Did you try launching the scheduled task manually? With script output enabled? What does the output say? Have you tried deleting the scheduled task and recreating it? Please, try these troubleshooting steps and post the results.

**Comment by pearlset79** [comment]
I'll be taking a look at it this weekend...haven't had the time yet.  I'll post them here for you.  Thanks!
