### ISSUE TITLE
87: The parameter is incorrect

### ISSUE THREAD

**Issue by AKA-Axanar** [alekdavis/PlexBackup#84]
After running for about an hour I get the following error message:
RUNAS ERROR: Unable to run - C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
87: The parameter is incorrect.

subdirs 1 and 4 are empty.  subdir 2 has 6 zip files in it. and subdir 3 has one .reg file in it.

does anyone know what the issue is?  the 87 does not appear to be the line number in the ps1 file.  at the end of the log file is this:
Script execution result:
  SUCCESS
Done.

which implies that it ran OK.  but the error message and the two empty subdirs 1 and 4  make me think that it did not.
Thanks for any help.
Steve

**Comment by alekdavis** [comment]
Please, see https://github.com/alekdavis/PlexBackup/issues/67

**Comment by AKA-Axanar** [comment]
I tried this from #67
runas /machine:amd64 /trustlevel:0x20000 "$Script:PlexServerPath"

and I got this error instead:
RUNAS ERROR: Unable to run - C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
216: This version of C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

Is the backup actually good despite subdirs 1 and 4 being empty?  If so I'll I'll ignore the error.  A while back I let Windows "upgrade" from Win 10 to Win 11.  What a mistake that was.  I hate Win 11.  I am backing up the Plex data so I can reinstall with Win 10 instead of Win 11.

Thank you for making this script.  It's very well written and is very useful to a lot of people.

**Comment by alekdavis** [comment]
Thanks. In 99% of cases folders 1 and 4 should be empty, so if you see the SUCCESS message, you should be fine, except that the PMS could not get started. Btw, I am running out=of-the box script on Windos 11 Pro and it works fine, so I'm wondering what is wrong on your system. Have you tried the `/machine:x86` parameter instead of amd64?

**Comment by alekdavis** [comment]
So, have you tried the x86 switch?

**Comment by AKA-Axanar** [comment]
not yet.  I'll try it and let you know.

**Comment by AKA-Axanar** [comment]
with /machine:x86 it gave me the help for runas.

PS D:\> .\PlexBackup.ps1                                                                                                RUNAS USAGE:

RUNAS [ [/noprofile | /profile] [/env] [/savecred | /netonly] ]
        /user:<UserName> program

RUNAS [ [/noprofile | /profile] [/env] [/savecred] ]
        /smartcard [/user:<UserName>] program

RUNAS [ [/machine:<MachineType>] ] /trustlevel:<TrustLevel> program

   /noprofile        specifies that the user's profile should not be loaded.
                     This causes the application to load more quickly, but
                     can cause some applications to malfunction.
   /profile          specifies that the user's profile should be loaded.
                     This is the default.
   /env              to use current environment instead of user's.
   /netonly          use if the credentials specified are for remote
                     access only.
   /savecred         to use credentials previously saved by the user.
   /smartcard        use if the credentials are to be supplied from a
                     smartcard.
   /user             <UserName> should be in form USER@DOMAIN or DOMAIN\USER
   /showtrustlevels  displays the trust levels that can be used as arguments
                     to /trustlevel.
   /trustlevel       <Level> should be one of levels enumerated
                     in /showtrustlevels.
   /machine          specifies the machine architecture of the process.
                     <MachineType> should be one of x86|amd64|arm|arm64.
   program           command line for EXE.  See below for examples

Examples:
> runas /noprofile /user:mymachine\administrator cmd
> runas /profile /env /user:mydomain\admin "mmc %windir%\system32\dsa.msc"
> runas /env /user:user@domain.microsoft.com "notepad \"my file.txt\""

NOTE:  Enter user's password only when prompted.
NOTE:  /profile is not compatible with /netonly.
NOTE:  /savecred is not compatible with /smartcard.

**Comment by alekdavis** [comment]
That's weird. I suspect there is something wrong in the command-line parameters. The `/machine` option is a misnomer here. It does not indicate the OS architecture. It is supposed to specify the architecture of the app: `amd64` for 64-bit apps, and `x86` for 32-bit apps. AFAIK, PMS has a 32-bit and a 64-bit version, so depending on the version you are using, one of these two flags should work. If I were to troubleshoot, I would've stopped PMS, and try to launch it from command line manually (and play with the flags):

```
runas /machine:amd64 /trustlevel:0x20000 "PATH TO PMS EXE"
```
or
```
runas /machine:x64 /trustlevel:0x20000 "PATH TO PMS EXE"
```

**Comment by AKA-Axanar** [comment]
this worked:
runas /machine:x86 /trustlevel:0x20000 "C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe"

**Comment by alekdavis** [comment]
So, if you change this line:
```
runas /trustlevel:0x20000 "$Script:PlexServerPath"
```
to
```
runas /machine:x86 /trustlevel:0x20000 "$Script:PlexServerPath"
```
it should work, too.

**Comment by AKA-Axanar** [comment]
yes.  
that is exactly what I tried last night.  I ran the full script using that change and the backup worked fine with no error.

**Comment by alekdavis** [comment]
Cool. I think I will add a switch for this since it happens to people once in a while.

**Comment by alekdavis** [comment]
Added a workaround in https://github.com/alekdavis/PlexBackup/releases/tag/v2.1.7.
