### ISSUE TITLE
Add the option to exclude Cache folder

### ISSUE THREAD

**Issue by SimonCouture993** [alekdavis/PlexBackup#89]
As mentionned in the Plex guide to do backup, we can exclude the Cache folder to save up space. If I'm not mistaken, we cannot do this with your script. It would be nice to have as a parameter to save some space during backup.

Here's the link to the plex article: https://support.plex.tv/articles/201539237-backing-up-plex-media-server-data/

Hope you consider adding this feature. Otherwise, love the script.

**Comment by albino1** [comment]
Take a look at this post:

https://github.com/alekdavis/PlexBackup/issues/47#issuecomment-820893956

**Comment by SimonCouture993** [comment]
Ahhh missed it thanks a lot!
