### ISSUE TITLE
Skip Cache Folder

### ISSUE THREAD

**Issue by blevins321** [alekdavis/PlexBackup#9]
Plex's documentation ([here](https://support.plex.tv/articles/201539237-backing-up-plex-media-server-data/?_ga=2.237987968.1668637795.1553264530-797115940.1548726532)) says that the cache folder can be skipped as it is simply regenerated the next time that Plex runs. Could the script skip backing up and/or restoring the Cache folder? It would save about 10 minutes of my backup time, and 6 gigs of storage for me. 

PS - 7zip compression is terrific - did my first backup using that method today and it was great :-)

**Comment by blevins321** [comment]
Disregard :-) . Just noticed the preferences option for ExcludePlexAppDataDirs and that works fine. Might I suggest having Cache as the sample value setting so that it's there by default?

**Comment by alekdavis** [comment]
Thanks for the feedback. I'll think about it. It may be a good idea (with exception of the test runs when you would want to keep cache).
