### ISSUE TITLE
Error running PMS after backup

### ISSUE THREAD

**Issue by whogots** [alekdavis/PlexBackup#91]
This script is great but since setting a new win 11 NUC it returns this error after a successful backup:

Unable to run - C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe 87: The parameter is incorrect.

Any ideas?

Cheers

**Comment by alekdavis** [comment]
See https://github.com/alekdavis/PlexBackup/releases/tag/v2.1.7

**Comment by whogots** [comment]
Thanks I'll try it
